### ISSUE TITLE
 It's not a problem! Only to follow the project and notifications

### ISSUE THREAD

**Issue by Guillerbr** [jaonoctus/exchange#4]
:)

**Comment by jaonoctus** [comment]
@Guillerbr thank you!

Just a tip, you can watch the github projects instead create an issue. Like that:
![screenshot from 2018-02-19 08-31-32](https://user-images.githubusercontent.com/7918067/36375766-60dda7a8-154f-11e8-9972-ab24ca9b286a.png)
